version: '3'

services:
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=example

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.2.3
    ports:
      - ${ES_PORT}:9200
      - 9300:9300
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1

  kibana:
    image: docker.elastic.co/kibana/kibana:8.2.3
    ports:
      - ${KIBANA_PORT}:5601
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch

  # server:
  #   build: ./server
  #   volumes:
  #     - ./server:/app
  #     - /app/node_modules
  #   ports:
  #     - 8000:8000
  #   command: yarn start
  #   depends_on:
  #     - db
  #     - elasticsearch
